### PR TITLE
Pre calculate fontSize for all scrambles fix #497

### LINKED ISSUE #497: Different font size and line breaks for some extra attempts
## Actual (problem) behavior
One set of scrambles I generated for Berlin Winter Cubing 2020 had both extra attempts written in smaller fonts and in one line.

## Expected behavior
All move sequences for one set of scrambles should have the same font size and have equal linebreaks. 

## Steps To Reproduce
Generate a lot of 3x3x3 Scrambles...

## Desktop (please complete the following information):
macOS, FF 72.01, TNoodle 0.15.1, Java Version 8 Update 241

## Sheet
[3x3x3 Cube Round 2 Scramble Set A.pdf](https://github.com/thewca/tnoodle/files/4083857/3x3x3.Cube.Round.2.Scramble.Set.A.pdf)

### PR DESCRIPTION
**Pull request by campos20**
This a quick fix and is not part of the big refactoring I'm doing #499

@Laura-O 's scrambles should look like this

[Scrambles for Berlin Winter Cubing 2020 - All Scrambles.pdf](https://github.com/thewca/tnoodle/files/4142047/Scrambles.for.Berlin.Winter.Cubing.2020.-.All.Scrambles.pdf)

A complete set of scrambles should look like this

[Scrambles for 2020-01-31 - All Scrambles.pdf](https://github.com/thewca/tnoodle/files/4142030/Scrambles.for.2020-01-31.-.All.Scrambles.pdf)

The fix idea is pretty simple: pre calculate font size using scrambleRequest.allScrambles instead of each part. I also set minimum one line font size to 15 because 12 looked unnecessarily tiny.

### CODE REVIEW

File: webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/FmcSolutionSheet.kt [hunk 1]
```diff
@@ -268,7 +268,7 @@ open class FmcSolutionSheet(request: ScrambleRequest, globalTitle: String?, loca
         val movesFont = Font(bf, movesFontSize.toFloat())
 
         val table = PdfPTable(columns).apply {
-            setTotalWidth(floatArrayOf(firstColumnWidth.toFloat(), *FloatArray(WCA_MOVES.size) { it -> cellWidth.toFloat() }))
```
Comment (suushiemaniac) [inline webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/FmcSolutionSheet.kt]: Nice catch!

File: webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/GeneralScrambleSheet.kt [hunk 2]
```diff
@@ -44,18 +43,18 @@ class GeneralScrambleSheet(scrambleRequest: ScrambleRequest, globalTitle: String
 
         val scrambleImageSize = scrambleRequest.scrambler.getPreferredSize(maxScrambleImageWidth, maxScrambleImageHeight)
 
-        // First check if any scramble requires highlighting.
-        val forceStdHighlighting = requiresHighlighting(availableWidth, scrambleImageSize, scrambleRequest.scrambles, STD_SCRAMBLE_PREFIX)
+        val indexColumnWidth = availableWidth / 20f
```
Comment (suushiemaniac) [inline webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/GeneralScrambleSheet.kt]: Where does that 20 come from?
I think it would make sense to (a) briefly document it and (b) move it into the companion object as a `const val`

File: webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/GeneralScrambleSheet.kt [hunk 3]
```diff
@@ -44,18 +43,18 @@ class GeneralScrambleSheet(scrambleRequest: ScrambleRequest, globalTitle: String
...
 
-        // Also check extra scrambles for visual consistency
-        val forceExtraHighlighting = requiresHighlighting(availableWidth, scrambleImageSize, scrambleRequest.extraScrambles, EXTRA_SCRAMBLE_PREFIX)
+        val scrambleColumnWidth = availableWidth - indexColumnWidth - scrambleImageSize.width.toFloat() - (2 * SCRAMBLE_IMAGE_PADDING).toFloat()
 
-        val useHighlighting = forceStdHighlighting || forceExtraHighlighting
+        val (scrambleFont, oneLine) = getFontConfiguration(scrambleColumnWidth, scrambleImageSize, scrambleRequest.allScrambles)
+
+        val useHighlighting = requiresHighlighting(scrambleColumnWidth, scrambleRequest.allScrambles, scrambleFont, oneLine)
```
Comment (suushiemaniac) [inline webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/GeneralScrambleSheet.kt]: nice catch on the deduplication of `getFontConfiguration`!

File: webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/GeneralScrambleSheet.kt [hunk 4]
```diff
@@ -128,22 +110,14 @@ class GeneralScrambleSheet(scrambleRequest: ScrambleRequest, globalTitle: String
...
 
-    fun requiresHighlighting(availableWidth: Float, scrambleImageSize: Dimension, scrambles: List<String>, scrambleNumberPrefix: String): Boolean {
-        val scrambleColumnWidth = getScrambleColumnWidth(availableWidth, scrambleImageSize, scrambles, scrambleNumberPrefix)
-        val (scrambleFont, oneLine) = getFontConfiguration(availableWidth, scrambleImageSize, scrambles, scrambleNumberPrefix)
-
+    fun requiresHighlighting(scrambleColumnWidth: Float, scrambles: List<String>, scrambleFont: Font, oneLine: Boolean): Boolean {
         val paddedScrambles = scrambles.map { if (oneLine) it else StringUtil.padTurnsUniformly(it, PdfUtil.NON_BREAKING_SPACE.toString()) }
         val lineChunks = paddedScrambles.map { it.splitToLineChunks(scrambleFont, scrambleColumnWidth) }
 
         return lineChunks.any { it.size >= MIN_LINES_TO_ALTERNATE_HIGHLIGHTING }
```
Comment (suushiemaniac) [inline webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/GeneralScrambleSheet.kt]: There _may_ be a bug here, since the example PDF you uploaded shows 3 lines without highlighting

File: webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/util/FontUtil.kt [hunk 5]
```diff
@@ -11,7 +11,7 @@ object FontUtil {
     val NOTO_SANS_FONT: BaseFont = BaseFont.createFont("fonts/NotoSans-Regular.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED)
 
     const val MAX_SCRAMBLE_FONT_SIZE = 20f
-    const val MINIMUM_ONE_LINE_FONT_SIZE = 12f
+    const val MINIMUM_ONE_LINE_FONT_SIZE = 15f
```
Comment (suushiemaniac) [inline webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/util/FontUtil.kt]: Please add a code comment with some (brief) form of reasoning why 15 was chosen. Seems pretty arbitrary otherwise.

**Comment by suushiemaniac** [comment]
> This a quick fix and is not part of the big refactoring I'm doing #499
> 
> @Laura-O 's scrambles should look like this
> 
> [Scrambles for Berlin Winter Cubing 2020 - All Scrambles.pdf](https://github.com/thewca/tnoodle/files/4115127/Scrambles.for.Berlin.Winter.Cubing.2020.-.All.Scrambles.pdf)

This PDF looks odd, because almost all scrambles use 3 lines and should thus be highlighted. Please debug and fix why highlighting is not used for `333` but then again _is used_ correctly for `333ni`

File: webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/util/FontUtil.kt (hunk 5 above)
Comment (campos20) [reply webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/util/FontUtil.kt]: This is a Util class with a const val. The name should be self explanatory. 12f looks tiny to squeeze scrambles in one line.

**Comment by campos20** [comment]
@suushiemaniac there's no bug. Highlight was calculated in advance for all scrambles so if 1/28 scrambles of 333mbf (therefore 333ni) had highlight all scrambles would be highlighted.

**Comment by campos20** [comment]
@suushiemaniac PDFs updated on the OP

**Comment by suushiemaniac** [comment]
Thanks, but I guess that was not my original problem. There was a misunderstanding about the minimum number of lines that are necessary for highlighting -- I thought it was 3 while it's actually 4.

I'm not sure how I feel about local/individual highlighting... Can we gather some more opinions on this?

**Comment by campos20** [comment]
Highlighting reverted. Updated on the OP.

**Comment by suushiemaniac** [comment]
Looking good now, feel free to rebase!
